# Generated by Django 3.2.3 on 2021-05-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orign_text', models.TextField()),
                ('src', models.CharField(max_length=10)),
                ('dest', models.CharField(max_length=10)),
                ('translated_text', models.TextField()),
            ],
        ),
    ]
